/**
 * ScaleCollectorDbServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type KitStatus = 'Wishlist' | 'Stash' | 'Started' | 'Finished' | 'Trash';

export const KitStatus = {
    Wishlist: 'Wishlist' as KitStatus,
    Stash: 'Stash' as KitStatus,
    Started: 'Started' as KitStatus,
    Finished: 'Finished' as KitStatus,
    Trash: 'Trash' as KitStatus
};