/**
 * ScaleCollectorDbServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KitStatus } from './kitStatus';
import { KitType } from './kitType';

export interface ModelKitPutRequest { 
    id?: number;
    type?: KitType;
    status?: KitStatus;
    manufacturerArticleNumber?: string;
    title?: string;
    scaleId?: number;
    brandId?: number;
}